### ISSUE TITLE
Keepout Filter Tutorial not working

### ISSUE THREAD

**Issue by PauloFavero** [ros-planning/navigation2#2421]
Hi,

I have an ros2 application with nav2 running inside a docker container.
Recently, I tried to implement the keepout filter tutorial but it is crashing when I try to run it. 

I did the following steps:

1. git clone the nav2/tutorials
2. ```colcon build```
3. . ```install/setup.sh```
4. ```ros2 launch nav2_costmap_filters_demo costmap_filter_info.launch.py params_file:=/paulo/workspace/src/nav2_costmap_filters_demo/params/keepout_params.yaml mask:=/paulo/workspace/src/nav2_costmap_filters_demo/maps/keepoutZones.yaml ```

At the step 4, I get the following error:

```
paulo@paulo:/paulo/workspace$ ros2 launch nav2_costmap_filters_demo costmap_filter_info.launch.py params_file:=/paulo/workspace/src/nav2_costmap_filters_demo/params/keepout_params.yaml mask:=/paulo/workspace/src/nav2_costmap_filters_demo/maps/paulo_keepoutZones.yaml

[INFO] [launch]: All log files can be found below /home/paulo/.ros/log/2021-06-23-03-45-47-759834-paulo-4741
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:271> exception=SubstitutionFailure("executable 'costmap_filter_info_server' not found on the libexec directory '/opt/ros/foxy/lib/nav2_map_server' ")>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 273, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 293, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 1 more time]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 442, in execute
    ret = super().execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 775, in execute
    self.__expand_substitutions(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 635, in __expand_substitutions
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 635, in <listcomp>
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_context.py", line 184, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/substitutions/executable_in_package.py", line 84, in perform
    raise SubstitutionFailure(
launch.substitutions.substitution_failure.SubstitutionFailure: executable 'costmap_filter_info_server' not found on the libexec directory '/opt/ros/foxy/lib/nav2_map_server' 
[INFO] [lifecycle_manager-1]: process started with pid [4743]
[INFO] [map_server-2]: process started with pid [4745]
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:271> exception=AttributeError("'NoneType' object has no attribute 'complete'")>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 273, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 293, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 422, in __on_signal_process_event
    if self._subprocess_protocol.complete.done():
AttributeError: 'NoneType' object has no attribute 'complete'
[INFO] [lifecycle_manager-1]: sending signal 'SIGINT' to process[lifecycle_manager-1]
[ERROR] [lifecycle_manager-1]: process has died [pid 4743, exit code -2, cmd '/opt/ros/foxy/lib/nav2_lifecycle_manager/lifecycle_manager --ros-args -r __node:=lifecycle_manager_costmap_filters -r __ns:=/ --params-file /tmp/launch_params_fuy6xp6x --params-file /tmp/launch_params_tegnjfn7 --params-file /tmp/launch_params_di9_nrvy'].
[map_server-2] [INFO] [1624419947.922638616] [filter_mask_server]: 
[map_server-2]  filter_mask_server lifecycle node launched. 
[map_server-2]  Waiting on external lifecycle transitions to activate
[map_server-2]  See https://design.ros2.org/articles/node_lifecycle.html for more information.
[map_server-2] [INFO] [1624419947.922779752] [filter_mask_server]: Creating
[ERROR] [map_server-2]: process[map_server-2] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [map_server-2]: sending signal 'SIGTERM' to process[map_server-2]
[ERROR] [map_server-2]: process has died [pid 4745, exit code -15, cmd '/opt/ros/foxy/lib/nav2_map_server/map_server --ros-args -r __node:=filter_mask_server -r __ns:=/ --params-file /tmp/tmppsnb_avr'].
```

From the error above, I think the most import is:

```
File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/substitutions/executable_in_package.py", line 84, in perform
    raise SubstitutionFailure(
launch.substitutions.substitution_failure.SubstitutionFailure: executable 'costmap_filter_info_server' not found on the libexec directory '/opt/ros/foxy/lib/nav2_map_server'
```

Any suggestions on how to fix it?

Thanks :)

**Comment by SteveMacenski** [comment]
> launch.substitutions.substitution_failure.SubstitutionFailure: executable 'costmap_filter_info_server' not found on the libexec directory '/opt/ros/foxy/lib/nav2_map_server' 

This is not available in Foxy, its only in Galactic or main. 

In the future, please post questions like this to ROS Answers or in the navigation.ros.org repo itself.
