### ISSUE TITLE
Could not import 'rosidl_typesupport_c' for package 'nav2_msgs'

### ISSUE THREAD

**Issue by m2-farzan** [ros-planning/navigation2#2942]
## Bug report

**Required Info:**

- Operating System:
  -  Ubuntu 20.04 (inside docker)
- ROS2 Version:
  -  galactic
- Version or commit hash:
  - ros-galactic-navigation2	1.0.8-1focal.20220430.173751
  - ros-galactic-nav2-msgs	1.0.8-1focal.20220430.165617

- DDS implementation:
  -  Fast-RTPS 

#### Steps to reproduce issue

```
#!/bin/python3

import rclpy
from nav2_simple_commander.robot_navigator import BasicNavigator

rclpy.init()
nav = BasicNavigator()
```

#### Expected behavior
Exit cleanly

#### Actual behavior
```
1651914735.930865 [0]    python3: selected interface "tap0" is not multicast-capable: disabling multicast
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py", line 46, in import_type_support
    return importlib.import_module(module_name, package=pkg_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /opt/ros/galactic/lib/libnav2_msgs__rosidl_generator_c.so: undefined symbol: geometry_msgs__msg__Pose__copy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 7, in <module>
    nav = BasicNavigator()
  File "/opt/ros/galactic/lib/python3.8/site-packages/nav2_simple_commander/robot_navigator.py", line 60, in __init__
    self.nav_through_poses_client = ActionClient(self,
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/action/client.py", line 148, in __init__
    check_for_type_support(action_type)
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/type_support.py", line 29, in check_for_type_support
    msg_or_srv_type.__class__.__import_type_support__()
  File "/opt/ros/galactic/lib/python3.8/site-packages/nav2_msgs/action/_navigate_through_poses.py", line 1319, in __import_type_support__
    module = import_type_support('nav2_msgs')
  File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py", line 48, in import_type_support
    raise UnsupportedTypeSupport(pkg_name)
rosidl_generator_py.import_type_support_impl.UnsupportedTypeSupport: Could not import 'rosidl_typesupport_c' for package 'nav2_msgs'
Exception ignored in: <function ActionClient.__del__ at 0x7fce4eb1fdc0>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/action/client.py", line 597, in __del__
    self.destroy()
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/action/client.py", line 588, in destroy
    if self._client_handle is None:
AttributeError: 'ActionClient' object has no attribute '_client_handle'
```

## Additional Info
The error showed up when I upgraded ros-galactic-nav2-msgs package from `1.0.8-1focal.20220211.060536` to `1.0.8-1focal.20220430.165617`.

**Comment by padhupradheep** [comment]
we recently had a new release `1.0.9` . Could you maybe give that a spin?
