### ISSUE TITLE
Planner Benchmark not working due to condition in if clause

### ISSUE THREAD

**Issue by Unknown-Student** [ros-planning/navigation2#3998]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04 (on WSL)
- ROS2 Version:
  - Humbel Binary
- Version or commit hash:
  - ros-humble-navigation2  1.1.12-1jammy.20231117.222305
- DDS implementation:
  - Cyclone DDS

#### Steps to reproduce issue
Run Nav2 Planner Benchmark according to the [tutorial ](https://github.com/ros-planning/navigation2/tree/main/tools/planner_benchmarking)

0. set up benchmark.yaml file
1. run ./planning_benchmark_bringup.py
2. start metric.py

#### Expected behavior
path is returned and 
```
[INFO] [1701617409.491591365] [basic_navigator]: Change map request was successful!
Cycle:  0 out of:  100
Start geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1701617411, nanosec=507115589), frame_id='map'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=22.100000329315662, y=63.40000094473362, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=-0.0, y=0.0, z=0.9149460091343314, w=-0.40357626338668606)))
Goal geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1701617411, nanosec=507115589), frame_id='map'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=91.05000135675073, y=88.65000132098794, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.7650602655255458, w=0.6439586866515439)))
[INFO] [1701617411.508249656] [basic_navigator]: Getting path...
Cycle:  1 out of:  100
Start geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1701617411, nanosec=507115589), frame_id='map'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=59.50000088661909, y=71.75000106915832, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=-0.0, y=0.0, z=0.28252338025045043, w=-0.9592604128243067)))
Goal geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1701617411, nanosec=507115589), frame_id='map'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=71.70000106841326, y=24.050000358372927, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=-0.0, y=0.0, z=0.29343911542801276, w=-0.9559777641435105)))
[INFO] [1701617411.760246602] [basic_navigator]: Getting path...
Cycle:  2 out of:  100
Start geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1701617411, nanosec=507115589), frame_id='map'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=37.85000056400895, y=56.50000084191561, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=-0.0, y=0.0, z=0.10599275217363893, w=-0.9943669023487546)))
Goal geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1701617411, nanosec=507115589), frame_id='map'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=54.250000808387995, y=59.05000087991357, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.9852462579855289, w=0.1711426630782422)))
[INFO] [1701617411.932378201] [basic_navigator]: Getting path...
```
[...]
```Cycle:  99 out of:  100
Start geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1701617411, nanosec=507115589), frame_id='map'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=89.75000133737922, y=94.55000140890479, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=-0.0, y=0.0, z=0.9658628410642968, w=-0.25905399485668035)))
Goal geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1701617411, nanosec=507115589), frame_id='map'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=92.70000138133764, y=21.65000032261014, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.06400001589102215, w=0.9979498975228911)))
[INFO] [1701617425.999613646] [basic_navigator]: Getting path...
Write Results...
Write Complete
```

#### Actual behavior
```[INFO] [1701616473.620062333] [basic_navigator]: Change map request was successful!
Cycle:  0 out of:  100
Start geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1701616475, nanosec=633565680), frame_id='map'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=22.100000329315662, y=63.40000094473362, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=-0.0, y=0.0, z=0.9149460091343314, w=-0.40357626338668606)))
Goal geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1701616475, nanosec=633565680), frame_id='map'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=91.05000135675073, y=88.65000132098794, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.7650602655255458, w=0.6439586866515439)))
[INFO] [1701616475.634594728] [basic_navigator]: Getting path...
Traceback (most recent call last):
  File "<path/to/file>/metric.py", line 146, in <module>
    main()
  File "<path/to/file>metric.py", line 125, in main
    result = getPlannerResults(navigator, start, goal, planners)
  File "<path/to/file>metric.py", line 34, in getPlannerResults
    if path is not None and path.error_code == 0:
AttributeError: 'ComputePathToPose_Result' object has no attribute 'error_code'
[ros2run]: Process exited with failure 1
```

#### Additional information
I managed to make the metric.py script run by editing line 34 and deleting the path.error_code == 0
```python
def getPlannerResults(navigator, initial_pose, goal_pose, planners):
    results = []
    for planner in planners:
        path = navigator._getPathImpl(initial_pose, goal_pose, planner, use_start=True)
        if path is not None and path.error_code == 0:
            results.append(path)
        else:
            print(planner, 'planner failed to produce the path')
            return results
    return result
``` 
to 
```python
def getPlannerResults(navigator, initial_pose, goal_pose, planners):
    results = []
    for planner in planners:
        path = navigator._getPathImpl(initial_pose, goal_pose, planner, use_start=True)
        if path is not None:
            results.append(path)
        else:
            print(planner, 'planner failed to produce the path')
            return results
    return results
```
I am not sure that with the removal of the condition the result would return some errors, but it did run. 
Hope I could help.

**Comment by SteveMacenski** [comment]
Use the proper branch and things will work fine: https://github.com/ros-planning/navigation2/blob/humble/tools/planner_benchmarking/metrics.py 🙂
