### ISSUE TITLE
Some of the Build Farm is failing due to builtin interfaces

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#442]
Well good work! Looks like nothing is failing due to yaml parsing, behavior trees, angles anymore! 

It's a little eyebrow raising that this fails on finding the builtin interfaces package which we don't directly touch. Anyone have thoughts? Full text in your email but it all looks good until rosdep for this.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 257, in __getitem__
    return self._weakref[key]
  File "/usr/lib/python3.6/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 'ros-crystal-builtin-interfaces'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 260, in __getitem__
    rawpkg = self._cache[key]
KeyError: 'ros-crystal-builtin-interfaces'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 266, in <module>
    main()
  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 126, in main
    get_binary_package_versions(apt_cache, debian_pkg_names))
  File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 144, in get_binary_package_versions
    pkg = apt_cache[debian_pkg_name]
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 262, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'ros-crystal-builtin-interfaces'"
Build step 'Execute shell' marked build as failure
```

**Comment by SteveMacenski** [comment]
As far as I can tell, all of the actual packages themselves succeeded given we only got emails on the navigation2 metapackage

**Comment by SteveMacenski** [comment]
Not action on our end. Someone else broke it and its coming around in the next few days
