### ISSUE TITLE
test_localization fails in CircleCI

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#628]
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue
See log here: https://circleci.com/gh/ros-planning/navigation2/388?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by crdelsey** [comment]
I ran the dockerhub image and ran `colcon test` locally in that image. I see the exact same ALSA errors, however the gzerver does not die and the test passes. The ALSA errors seem to be a red herring.

The messages I get when I run locally are
```
Error Code: 11 Msg: Unable to find uri[model://turtlebot3_world]
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
[INFO] [turtlebot3_diff_drive]: Subscribed to [/cmd_vel]
[INFO] [turtlebot3_diff_drive]: Advertise odometry on [/odom]
[INFO] [turtlebot3_diff_drive]: Publishing odom transforms between [odom] and [base_footprint]
[INFO] [turtlebot3_joint_state]: Going to publish joint [wheel_left_joint]
[INFO] [turtlebot3_joint_state]: Going to publish joint [wheel_right_joint]
```

In circleCI gzserver fails between the last ALSA message and the first turtlebot3_diff_drive message.

**Comment by crdelsey** [comment]
If I run `gzserver` in CircleCI without sourcing `/opt/nav2_ws/install/setup.bash`, it runs OK. If I source it though, `gzserver` segfaults. Here's the backtrace

```
(gdb) bt
#0  0x00007ffe9a5eab49 in rclcpp::SubscriptionFactory rclcpp::create_subscription_factory<geometry_msgs::msg::Twist_<std::allocator<void> >, std::_Bind<void (gazebo_plugins::GazeboRosDiffDrivePrivate::*(gazebo_plugins::GazeboRosDiffDrivePrivate*, std::_Placeholder<1>))(std::shared_ptr<geometry_msgs::msg::Twist_<std::allocator<void> > >)>, std::allocator<void>, geometry_msgs::msg::Twist_<std::allocator<void> >, rclcpp::Subscription<geometry_msgs::msg::Twist_<std::allocator<void> >, std::allocator<void> > >(std::_Bind<void (gazebo_plugins::GazeboRosDiffDrivePrivate::*(gazebo_plugins::GazeboRosDiffDrivePrivate*, std::_Placeholder<1>))(std::shared_ptr<geometry_msgs::msg::Twist_<std::allocator<void> > >)>&&, rclcpp::message_memory_strategy::MessageMemoryStrategy<geometry_msgs::msg::Twist_<std::allocator<void> >, std::allocator<void> >::SharedPtr, std::shared_ptr<std::allocator<void> >)::{lambda(rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&)#1}::operator()(rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&) const ()
   at /opt/ros_ws/install/gazebo_plugins/lib/libgazebo_ros_diff_drive.so
#1  0x00007ffe9a5eac83 in std::_Function_handler<std::shared_ptr<rclcpp::SubscriptionBase> (rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&), rclcpp::SubscriptionFactory rclcpp::create_subscription_factory<geometry_msgs::msg::Twist_<std::allocator<void> >, std::_Bind<void (gazebo_plugins::GazeboRosDiffDrivePrivate::*(gazebo_plugins::GazeboRosDiffDrivePrivate*, std::_Placeholder<1>))(std::shared_ptr<geometry_msgs::msg::Twist_<std::allocator<void> > >)>, std::allocator<void>, geometry_msgs::msg::Twist_<std::allocator<void> >, rclcpp::Subscription<geometry_msgs::msg::Twist_<std::allocator<void> >, std::allocator<void> > >(std::_Bind<void (gazebo_plugins::GazeboRosDiffDrivePrivate::*(gazebo_plugins::GazeboRosDiffDrivePrivate*, std::_Placeholder<1>))(std::shared_ptr<geometry_msgs::msg::Twist_<std::allocator<void> > >)>&&, rclcpp::message_memory_strategy::MessageMemoryStrategy<geometry_msgs::msg::Twist_<std::allocator<void> >, std::allocator<void> >::SharedPtr, std::shared_ptr<std::allocator<void> >)::{lambda(rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&)#1}>::_M_invoke(std::_Any_data const&, rclcpp::node_interfaces::NodeBaseInterface*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&) () at /opt/ros_ws/install/gazebo_plugins/lib/libgazebo_ros_diff_drive.so
#2  0x00007fffbf8678e2 in std::function<std::shared_ptr<rclcpp::SubscriptionBase> (rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&)>::operator()(rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&) const (__args#2=..., __args#1=..., __args#0=<optimized out>, this=0x7ffe9b7fbbc0)
   at /usr/include/c++/7/bits/std_function.h:706
#3  0x00007fffbf8678e2 in rclcpp::node_interfaces::NodeTopics::create_subscription(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::SubscriptionFactory const&, rcl_subscription_options_t&, bool) (this=0x7ffe904891f0, topic_name=..., subscription_factory=..., subscription_options=..., use_intra_process=<optimized out>) at /home/jenkins-agent/workspace/packaging_linux/ws/src/ros2/rclcpp/rclcpp/src/rclcpp/node_interfaces/node_topics.cpp:91
#4  0x00007ffe9a5eb811 in std::shared_ptr<rclcpp::Subscription<geometry_msgs::msg::Twist_<std::allocator<void> >, std::allocator<void> > > rclcpp::create_subscription<geometry_msgs::msg::Twist_<std::allocator<void> >, std::_Bind<void (gazebo_plugins::GazeboRosDiffDrivePrivate::*(gazebo_plugins::GazeboRosDiffDrivePrivate*, std::_Placeholder<1>))(std::shared_ptr<geometry_msgs::msg::Twist_<std::allocator<void> > >)>, std::allocator<void>, geometry_msgs::msg::Twist_<std::allocator<void> >, rclcpp::Subscription<geometry_msgs::msg::Twist_<std::allocator<void> >, std::allocator<void> > >(rclcpp::node_interfaces::NodeTopicsInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Bind<void (gazebo_plugins::GazeboRosDiffDrivePrivate::*(gazebo_plugins::GazeboRosDiffDrivePrivate*, std::_Placeholder<1>))(std::shared_ptr<geometry_msgs::msg::Twist_<std::allocator<void> > >)>&&, rmw_qos_profile_t const&, std::shared_ptr<rclcpp::callback_group::CallbackGroup>, bool, bool, rclcpp::message_memory_strategy::MessageMemoryStrategy<geometry_msgs::msg::Twist_<std::allocator<void> >, std::allocator<void> >::SharedPtr, std::shared_ptr<std::allocator<void> >) () at /opt/ros_ws/install/gazebo_plugins/lib/libgazebo_ros_diff_drive.so
#5  0x00007ffe9a5ebc50 in std::shared_ptr<rclcpp::Subscription<geometry_msgs::msg::Twist_<std::allocator<void> >, std::allocator<void> > > rclcpp::Node::create_subscription<geometry_msgs::msg::Twist_<std::allocator<void> >, std::_Bind<void (gazebo_plugins::GazeboRosDiffDrivePrivate::*(gazebo_plugins::GazeboRosDiffDrivePrivate*, std::_Placeholder<1>))(std::shared_ptr<geometry_msgs::msg::Twist_<std::allocator<void> > >)>, std::allocator<void>, rclcpp::Subscription<geometry_msgs::msg::Twist_<std::allocator<void> >, std::allocator<void> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Bind<void (gazebo_plugins::GazeboRosDiffDrivePrivate::*(gazebo_plugins::GazeboRosDiffDrivePrivate*, std::_Placeholder<1>))(std::shared_ptr<geometry_msgs::msg::Twist_<std::allocator<void> > >)>&&, rmw_qos_profile_t const&, std::shared_ptr<rclcpp::callback_group::CallbackGroup>, bool, rclcpp::message_memory_strategy::MessageMemoryStrategy<rclcpp::subscription_traits::has_message_type<std::_Bind<void (gazebo_plugins::GazeboRosDiffDrivePrivate::*(gazebo_plugins::GazeboRosDiffDrivePrivate*, std::_Placeholder<1>))(std::shared_ptr<geometry_msgs::msg::Twist_<std::allocator<void> > >)> >::type, std::allocator<void> >::SharedPtr, std::shared_ptr<std::allocator<void> >) ()
   at /opt/ros_ws/install/gazebo_plugins/lib/libgazebo_ros_diff_drive.so
#6  0x00007ffe9a5dfbf4 in gazebo_plugins::GazeboRosDiffDrive::Load(boost::shared_ptr<gazebo::physics::Model>, std::shared_ptr<sdf::Element>) () at /opt/ros_ws/install/gazebo_plugins/lib/libgazebo_ros_diff_drive.so
#7  0x00007ffff5ac74b1 in gazebo::physics::Model::LoadPlugin(std::shared_ptr<sdf::Element>) () at /usr/lib/x86_64-linux-gnu/libgazebo_physics.so.9
#8  0x00007ffff5ac9ea0 in gazebo::physics::Model::LoadPlugins() () at /usr/lib/x86_64-linux-gnu/libgazebo_physics.so.9
#9  0x00007ffff5b0ddca in gazebo::physics::World::LoadPlugins() () at /usr/lib/x86_64-linux-gnu/libgazebo_physics.so.9
#10 0x00007ffff5b1ae5d in gazebo::physics::World::Step() () at /usr/lib/x86_64-linux-gnu/libgazebo_physics.so.9
#11 0x00007ffff5b1b1cd in gazebo::physics::World::RunLoop() () at /usr/lib/x86_64-linux-gnu/libgazebo_physics.so.9
#12 0x00007ffff69a157f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff5dfd6db in start_thread (arg=0x7ffe9b7fe700) at pthread_create.c:463
#14 0x00007ffff63fc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
``` 

I suspect there is some incompatibility between the library the diff drive plugin compiled with, versus what gets run.
